
# [Default]

train:
  epochs: 50 # [100]
  batch_size: 16 # [8]
  eval_batch_size: 16 #[8]
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4 
  channels: 32 #[64]
  nheads: 4 #[8]
  diffusion_embedding_dim: 64 #[128]
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: True

model:
  is_pseudo_unconditional: 1
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  num_sample_features: 64
  n_condit_features: None

weaver:
  included: False
  d_meta: 64
  meta_encoder_n_heads: 2
  meta_encoder_n_layers: 2

