
# [Default]

train:
  epochs: 100 # Default: 100, I have tried more epochs (200)
  batch_size: 8 
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50 # Default: 50, maybe I'll try less so less time for error to accumulate
  schedule: "quad"
  is_linear: True

model:
  is_pseudo_unconditional: 1
  timeemb: 128 # Default: 128, I'm trying more dimensions
  featureemb: 16 # Default: 16, I'm trying more dimensions
  target_strategy: "test"
  num_sample_features: 64

weaver:
  included: False
  d_meta: 64
  meta_encoder_n_heads: 2
  meta_encoder_n_layers: 2

